### ISSUE TITLE
Unnecessaries resource files

### ISSUE THREAD

**Issue by nquinquenel** [Visp9/KZ-Tribe#10]
Keep only the needed bootstrap files in each folders:

- js/bootstrap.min.js
- css/bootstrap.min.css

Remove bootstrap/ folder

**Comment by xjose93** [comment]
Thanks, done by @dusanio at https://github.com/Visp9/KZ-Tribe/commit/d1bef86ad5ffa29989119bf5ac229f814795000e

**Comment by nquinquenel** [comment]
The js/ folder still contains a bunch of redundant and not used files, I'd recommend to keep only the bootstrap.min.js as I recommended, unless we make use of the other resource files (which is not the case yet)

**Comment by nquinquenel** [comment]
Same goes for the css folder

**Comment by Visp9** [comment]
Thanks @nquinquenel i missed a few. Its now cleaned.

**Comment by nquinquenel** [comment]
I don't think you pushed the modifications, also take care of the js resource file used, if you keep bootstrap.min.js you'll have to modify `<script src="js/bootstrap.bundle.js"></script>` in index.html accordingly

**Comment by Visp9** [comment]
@nquinquenel it is on line 38?

**Comment by Visp9** [comment]
@dusanio can you commit the changes?

**Comment by Visp9** [comment]
Can i close this?

**Comment by dusanio** [comment]
Yes

**Comment by nquinquenel** [comment]
No this is still not correct, the imported script resource in index.html doesn't exist anymore, you have to change it to bootstrap.min.js

**Comment by dusanio** [comment]
> No this is still not correct, the imported script resource in index.html doesn't exist anymore, you have to change it to bootstrap.min.js

Done, excuse me for that miss :/
