### ISSUE TITLE
Hook stops the timer instead of pausing the run

### ISSUE THREAD

**Issue by Visp9** [Visp9/KZ-Tribe#14]
Should pause the timer if you hook. Right now in plugin hook = cheat and then it stops it.

**Comment by xjose93** [comment]
Now it will stop timer if not paused when using hook.

Must test and give feedback!

**Comment by Visp9** [comment]
The timer should be paused if you click +hook @xjose93. But this might be a problem because if you pause you are basicly stuck on the same place as you /pause. You cant move and unpause to get teleported back.

**Comment by xjose93** [comment]
Modified, will pause timer if you use hook.
