### ISSUE TITLE
Console spam!

### ISSUE THREAD

**Issue by rvnd001** [Visp9/KZ-Tribe#16]
Server is spamming this in my console. Idk if it's the same for others.

hud_centerid is a privileged variable
hud_centerid is a privileged variable
hud_centerid is a privileged variable
hud_centerid is a privileged variable
Server tried to send invalid command:"developer 0;fps_max 99.5;cl_forwardspeed 400;cl_sidespeed 400;cl_backspeed 400
"
hud_centerid is a privileged variable
hud_centerid is a privileged variable
hud_centerid is a privileged variable
hud_centerid is a privileged variable

**Comment by Visp9** [comment]
@rvnd001 used cl_filerstuffcmd 1 wich plugin cant handle to force to 0 so spamming because of that. Fixed with a change.
