### ISSUE TITLE
RTV plugin does not change map when time is out

### ISSUE THREAD

**Issue by Visp9** [Visp9/KZ-Tribe#19]
seems like its waiting for round to end so it never change because we dont force new rounds. Dont find any good cmd in .cfg to fix this. Might need to redo some stuff in source.

**Comment by Visp9** [comment]
[galileo.zip](https://github.com/Visp9/KZ-Tribe/files/6759925/galileo.zip)

If someone find what ever i missed in this cfg, please tell me.

**Comment by xjose93** [comment]
Fixed with **gal_endonround 0** ; it was 1.
