### ISSUE TITLE
Can't /cp on ladders

### ISSUE THREAD

**Issue by rvnd001** [Visp9/KZ-Tribe#26]
Enable checkpoints on ladders

**Comment by rvnd001** [comment]
Fixed

**Comment by xjose93** [comment]
You can't save checkpoint while are on air, but can do it on ladders.

**Comment by xjose93** [comment]
@rvnd001 you are right, on ladder from **kzz_joebhop** you can't save cp and it says "You can not do checkpoints on bhop block".

Fixed.
