### ISSUE TITLE
map_id = 0 on some pro/nub records in db

### ISSUE THREAD

**Issue by Visp9** [Visp9/KZ-Tribe#5]
Dont know if it is related but player ArvInD got a pro1 but printed it was pro2 and then bot didnt start even tho he was the only pro time in db.

"[KZ-Tribe] ArvInD finished the map in 01:58.21 ( CPs: 0 | TPs: 0 | Weapon: USP [250])MOUSE2 is unbound.
[KZ-Tribe] ArvInD is now 2 in Professional Top
    here is the console print"

![unknown](https://user-images.githubusercontent.com/46937387/124098412-d0ceeb00-da5c-11eb-9403-d6db6dbd6d02.png)

**Comment by xjose93** [comment]
Fixed, must test it.

**Comment by Visp9** [comment]
Works
