### ISSUE TITLE
WR Bot is stuck in start of fof_chillbhop

### ISSUE THREAD

**Issue by Visp9** [Visp9/KZ-Tribe#7]
Just fly in the air in spawn

**Comment by xjose93** [comment]
It seems working:
![image](https://user-images.githubusercontent.com/707423/124191216-c4ca4400-dac3-11eb-9661-01c2fc3ea912.png)

**Comment by Visp9** [comment]
I didnt see this again since we restart server. Might happend bot doesnt join and just stay in spec but then just ask bot to join and it works. I close this for now.
