### ISSUE TITLE
Custom /setstart not functioning properly

### ISSUE THREAD

**Issue by rvnd001** [Visp9/KZ-Tribe#9]
When you press 6 in the /menu to set a custom start point, some thing like this pops up in chat "[KZ-Tribe] Set point. CLICK button to confirm" and we weren't able to set a custom start point. 

Typing /setstart does work initially but after you press start timer after setting your custom start point, it some how deletes the custom point set and you can't use the custom start again unless you set it again manually.

**Comment by Visp9** [comment]
@rvnd001 @ArvInD I dont get this when im trying. If i say /menu and click 6 its spectate?

**Comment by arvind** [comment]
Wrong arvind tagged.

**Comment by Visp9** [comment]
Sorry @arvind , but now you are a part of KZ-Tribe!

**Comment by xjose93** [comment]
@rvnd001 try now and give us feedback please :).

**Comment by rvnd001** [comment]
Yes, it's working now perfectly now :)
